server:
  port: 8769
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 300
      min-spare: 2
    accept-count: 200
    max-connections: 600

spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "tiger"

eureka:
  instance:
    hostname: admin
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}

  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:1001/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always