server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 300
      min-spare: 2
    accept-count: 200
    max-connections: 600

spring:
  application:
    name: hello-consumer-feign

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

